package com.vamaju.task.presentation.theme

import androidx.compose.ui.graphics.Color

val Lime = Color(0xFF2AC527)
val SunsetOrange = Color(0xFFFF5B5B)

val SurfaceLight = Color(0xFFD9DCE0)
val OnSurfaceLight = Color(0xFF0C0E1B)
val SurfaceVariantLight = Color(0xFFDEDEDE)
val OnSurfaceVariantLight = Color(0xFF004989)
val PrimaryContainerLight = Color(0xFFBBBBBB)
val OnPrimaryContainerLight = Color(0xFF0C0E1B)
val SecondaryContainerLight = Color(0xFFD9DCE0)
val OnSecondaryContainerLight = Color(0xFF0C0E1B)
val BackgroundLight = Color(0xFFF8FAFD)
val OnBackgroundLight = Color(0xFF0C0E1B)
val PrimaryLight = Color(0xFF0079BC)
val OnPrimaryLight = Color(0xFFFFFFFF)
val InversePrimaryLight = Color(0xFF56B9EF)
val SecondaryLight = Color(0xFFE87754)
val OnSecondaryLight = Color(0xFFE87754)
val TertiaryLight = Color(0xFF2997FF)
val OnTertiaryLight = Color(0xFF2997FF)

val ErrorForm = Color(0xFFd16a62)

val SurfaceDark = Color(0xFF212121)
val OnSurfaceDark = Color(0xFFFFFFFF)
val SurfaceVariantDark = Color(0xFF2B2F35)
val OnSurfaceVariantDark = Color(0xFF6ACAEA)
val PrimaryContainerDark = Color(0xFF3F444C)
val OnPrimaryContainerDark = Color(0xFF6ACAEA)
val SecondaryContainerDark = Color(0xFF303236)
val OnSecondaryContainerDark = Color(0xFFFFFFFF)
val BackgroundDark = Color(0xFF1E232A)
val OnBackgroundDark = Color(0xFFFFFFFF)
val PrimaryDark = Color(0xFF79CFEC)
val OnPrimaryDark = Color(0xFF252225)
val InversePrimaryDark = Color(0xFF70CCEB)
val SecondaryDark = Color(0xFFF09275)
val OnSecondaryDark = Color(0xFFEF8B6C)
val TertiaryDark = Color(0xFF66B4FF)
val OnTertiaryDark = Color(0xFF5CAFFF)